---
title: "R Notebook"
output: html_notebook
---

```{r libraries}
library(tidyverse)
```


```{r data}
townsville_complaints <- read_csv("data/animal_complaints.csv")
brisbane_complaints <- read_csv("data/brisbane_complaints.csv")
rspca_outcomes <- read_csv("data/animal_outcomes.csv")
```

```{r cleaning}
rspca_clean <- rspca_outcomes %>% 
  janitor::clean_names() %>% 
  group_by(year, animal_type, outcome) %>% 
  mutate(total = sum(c(act,nsw,nt,qld,sa,tas,vic,wa), na.rm = TRUE)) %>% 
  ungroup()

brisbane_complaints %>% 
  select(-c(nature, responsible_office, city, date_range)) %>% 
  mutate(category = replace_na(category, "Not Provided")) %>% 
  group_by(animal_type, category) %>% 
  summarise(count = n())

townsville_complaints %>% 
  janitor::clean_names() %>%
  group_by(date_received) %>% 
  separate(date_received, c("month", "year"), sep = " ", remove = FALSE)
```

```{r}
unique(rspca_clean$animal_type)

rspca_clean %>%
  filter(animal_type == "Dogs") %>%
  ggplot(aes(x = year, y = total, colour = outcome)) +
  geom_line() +
  theme_classic()
```

Everything except Wildlife -

Currently in Care is incomplete - starts in 2009
In stock only exists for 2002 - 2008
Transferred is incomplete - starts in 2002

Wildlife
Different stats --
No Reclaimed, Rehome
Has Released
Rest the same

Can do euthanization comparisons across them all. 


```{r}
rspca_clean %>%
  filter(animal_type == "Other Animals" & outcome == "Currently In Care")

```

